DerinDenizProjesiYeni/DerinDenizProjesi/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace DerinDenizProjesi.Controllers
{
    public class LanguageController : Controller
    {
        // GET: Language
        public ActionResult Change(String languageSelect)
        {
            if (languageSelect != null)
            {
                Thread.CurrentThread.CurrentCulture = CultureInfo.CreateSpecificCulture(languageSelect);
                Thread.CurrentThread.CurrentUICulture = new CultureInfo(languageSelect);
            }

            HttpCookie cookie = new HttpCookie("language");
            cookie.Value = languageSelect;
            Response.Cookies.Add(cookie);

            return RedirectToAction("Index","Home");
        }
    }
}

DerinDenizProjesiYeni/DerinDenizProjesi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/Layout.css" />
    @* <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>*@
   
    
    <title>@ViewBag.Title - Derin Deniz</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-derinDeniz navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header ">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("DerinDeniz", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav ">
                    <li>@Html.ActionLink(DerinDenizProjesi.Resources.Cokludil.Home, "Index", "Home")</li>
                    <li>@Html.ActionLink(DerinDenizProjesi.Resources.Cokludil.About, "About", "Home")</li>    
                    <li>@Html.ActionLink(DerinDenizProjesi.Resources.Cokludil.Contact, "Contact", "Home")</li>
                    <li>@Html.ActionLink(DerinDenizProjesi.Resources.Cokludil.Fishing, "Fishing", "Home")</li>
                    <li>@Html.ActionLink(DerinDenizProjesi.Resources.Cokludil.Dive, "Dive", "Home")</li>
                    
                    @if (Session["KulAdi"] == null)
                    {
                        <li>@Html.ActionLink(DerinDenizProjesi.Resources.Cokludil.Register, "Uye", "Home")</li>
                        <li>@Html.ActionLink(DerinDenizProjesi.Resources.Cokludil.Login, "Login", "Home")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink(DerinDenizProjesi.Resources.Cokludil.Logout, "Cikis", "Home")</li>
                    }
                    
                        
                  
                </ul>
                <div class="nav navbar-nav navbar-right col-md-4">
                    <div class="col-md-3 "> 
                        <div class="dropdown">
                            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="position:relative; top:8px;">
                                Dil
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                @Html.ActionLink("English", "Change", "Language", new { languageSelect = "en" }, null)
                                @Html.ActionLink("Türkçe", "Change", "Language", new { languageSelect = "tr" }, null)
                                
                            </ul>
                        </div>       
                    </div>
                    <div class="col-md-9">
                        <div class="input-group" style="position:relative; top:8px;">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">Ara</button>
                            </span>
                            <input type="text" class="form-control" placeholder="Search for...">
                        </div>

                    </div>
                    
                    
                </div>
                @*@Html.Partial("_LoginPartial")*@
            </div>
            
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="panel panel-default">
                <div class="panel-footer" style="color:black">
                    <p style="text-align:center; " >&copy;@DateTime.Now.Year - DerinDeniz</p>
                </div>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>